name: Release

on:
  release:
    types:
      - created

jobs:
  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github registry
      uses: docker/login-action@v1 
      with:
        username: ${{ github.actor }}
        password:  ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
        ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
        ghcr.io/${{ github.repository }}:latest

  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-20.04
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: swiftwasm/carton
          tap: swiftwasm/homebrew-tap
          formula: carton.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}

  bigsur_bottle:
    name: Build and distribute Homebrew bottle for macOS Big Sur
    runs-on: macos-11
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew install --build-bottle --verbose swiftwasm/tap/carton
          brew bottle swiftwasm/tap/carton
          mv ./carton--${{ github.event.release.tag_name }}.big_sur.bottle*.tar.gz \
            ./carton--${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./carton--${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
          asset_name: carton-${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
          asset_content_type: application/gzip

  update_formula_bigsur_bottle:
    name: Update the Homebrew formula again with bottle for Big Sur
    runs-on: ubuntu-20.04
    needs: [bigsur_bottle]
    steps:
      - uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: swiftwasm/carton
          tap: swiftwasm/homebrew-tap
          formula: carton.rb
          message: |
            Add bottle for carton ${{ github.event.release.tag_name }}
            on macOS Big Sur
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
